spring.datasource.url=jdbc:postgresql://dpg-daup677lk1mc73dohnn0-a.oregon-postgres.render.com:5432/smartstudentpaantry
spring.datasource.username=smartstudentpaantry_user
spring.datasource.password=jD3c37R3jpuaLVWXXuhPB6vwqV7SN9br
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=${PORT:8080}