server.port=9090

# PostgreSQL Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/pantrydb
spring.datasource.username=postgres
spring.datasource.password=Elona@2004

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true